title: "Andras Pokorny"
description: "designer"

# theme: jekyll-theme-console

plugins:
  - jekyll-seo-tag

header_pages:
  - work.md
  - thought.md
  - experience.md
  - index.md

footer: "keep in touch"

style: light
