title: "Andras Pokorny"
description: "designer"

theme: jekyll-theme-console

plugins:
  - jekyll-seo-tag

header_pages:
  - index.md
  - work.md
  - thought.md
  - experience.md

footer: "follow me"

style: light
